[package]
name = "path_minter"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.11.2"
pulse = { git ="https://github.com/inshell-art/pulse.git", tag="v0.1.4" }  

[dev-dependencies]
snforge_std = "0.40.0"
assert_macros = "2.11.2"

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]