[package]
name = "path_minter"
version.workspace = true
edition.workspace = true

[dependencies]
starknet.workspace = true
openzeppelin.workspace = true
path_interfaces.workspace = true
path_nft.workspace = true

[dev-dependencies]
snforge_std.workspace = true
assert_macros.workspace = true

[[target.starknet-contract]]
sierra = true
casm = true

[[target.test]]
build-external-contracts = ["path_nft::path_nft::PathNFT"]

[[target.lib]]

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
