[package]
name = "path_pulse_e2e"
version = "0.1.0"
edition.workspace = true

[dependencies]
starknet.workspace = true
openzeppelin.workspace = true
snforge_std.workspace = true
path_nft.workspace = true
path_minter.workspace = true
path_minter_adapter.workspace = true
pulse_auction.workspace = true
pulse_adapter.workspace = true
path_interfaces.workspace = true
path_test_support.workspace = true

[dev-dependencies]
assert_macros.workspace = true

[[test]]
name = "e2e_unit"
test-type = "unit"
build-external-contracts = [
    "path_nft::path_nft::PathNFT",
    "path_minter::path_minter::PathMinter",
    "pulse_auction::pulse_auction::PulseAuction",
    "path_minter_adapter::path_minter_adapter::PathMinterAdapter",
    "path_test_support::test_support::TestERC721Receiver",
]
