[package]
name = "path_nft"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.11.2"
openzeppelin = "1.0.0"

[dev-dependencies]
snforge_std = "0.40.0"
assert_macros = "2.11.2"

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]